### ISSUE TITLE
How to mount to an existing directory?

### ISSUE THREAD

**Issue by Slyke** [kubernetes-sigs/nfs-subdir-external-provisioner#113]
Hello,

Having trouble figuring our how to mount to an existing NFS directory. I have a K3s setup with a bunch of Raspberry Pis and a Synology NAS with NFS. I have successfully setup provisioning so that each pod gets some storage space on the NAS. A folder is automatically created, that I can use to house the files that the pods need.

Now here's my problem: I can't figure out how to set it up so that I can mount an existing directory. I have a Duplicati pod running in the cluster, and while I can have its config directory created and running fine, I can't figure out how to make this provisioner mount an existing directory that's on my NAS so I can create a PV and PVC for Duplicati. I have a bunch of photos that I want Duplicati to keep synced (among other things I need backed up).

Can anyone point me in the right direction?

I did see https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/5 but when I use ` --set storageClass.pathPattern=""` to setup my second NFS mount, it doesn't seem to do anything, the PVC just creates a folder in that directory.

**Comment by Slyke** [comment]
Figured out a easy way:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-photos-pvc
  namespace: default
spec:
  storageClassName: ""
  volumeName: test-photos-pv
  accessModes:
   - ReadWriteOnce 
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-photos-pv
  namespace: default
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3 # You may need to update this
  nfs:
    server: 10.8.10.10
    path: "/volume1/Photos"
    readOnly: false
```
