### ISSUE TITLE
ExternalProvisioning  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "k8s-sigs.io/nfs-subdir-external-provisioner" or manually created by system administrator

### ISSUE THREAD

**Issue by borch84** [kubernetes-sigs/nfs-subdir-external-provisioner#114]
Hi, I am trying to create a pvc but I get this message:

```
$ kubectl describe pvc idlcgrafana-pv
Name:          idlcgrafana-pv
Namespace:     default
StorageClass:  managed-nfs-storage
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    idlcgrafana-6c5c75744b-t6fpr
Events:
  Type    Reason                Age                From                         Message
  ----    ------                ----               ----                         -------
  Normal  ExternalProvisioning  14s (x2 over 29s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "k8s-sigs.io/nfs-subdir-external-provisioner" or manually created by system administrator
  Normal  ExternalProvisioning  8s (x3 over 36s)   persistentvolume-controller  waiting for a volume to be created, either by external provisioner "k8s-sigs.io/nfs-subdir-external-provisioner" or manually created by system administrator
```
These are the storage class, provisioner status and pvc:

SC:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  onDelete: delete
```

Provisioner pod:
```
$ kubectl describe po nfs-subdir-external-provisioner-7d659d475-bs7g4
Name:         nfs-subdir-external-provisioner-7d659d475-bs7g4
Namespace:    default
Priority:     0
Node:         gke-px-sync-default-pool-5afcf177-zl6m/10.142.0.16
Start Time:   Tue, 22 Jun 2021 14:29:00 -0600
Labels:       app=nfs-subdir-external-provisioner
              pod-template-hash=7d659d475
              release=nfs-subdir-external-provisioner
Annotations:  <none>
Status:       Running
IP:           10.80.0.15
IPs:
  IP:           10.80.0.15
Controlled By:  ReplicaSet/nfs-subdir-external-provisioner-7d659d475
Containers:
  nfs-subdir-external-provisioner:
    Container ID:   docker://246460c8c6ed3f8f6fd2e05f9bcc713e4e3d3d2b2d0c3702152f1c6b26accad2
    Image:          k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
    Image ID:       docker-pullable://k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner@sha256:63d5e04551ec8b5aae83b6f35938ca5ddc50a88d85492d9731810c31591fa4c9
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 22 Jun 2021 14:29:06 -0600
    Ready:          True
    Restart Count:  0
    Environment:
      PROVISIONER_NAME:  cluster.local/nfs-subdir-external-provisioner
      NFS_SERVER:        10.142.0.18
      NFS_PATH:          /home/borch
    Mounts:
      /persistentvolumes from nfs-subdir-external-provisioner-root (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from nfs-subdir-external-provisioner-token-25g9c (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  nfs-subdir-external-provisioner-root:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    10.142.0.18
    Path:      /home/borch
    ReadOnly:  false
  nfs-subdir-external-provisioner-token-25g9c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  nfs-subdir-external-provisioner-token-25g9c
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>
```

PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idlcgrafana-pv
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
```

I was able to mount the nfs exported folder into one of my workers nodes.

Let me know if you find something incorrect.

Cheers.
