### ISSUE TITLE
"onDelete: Delete"-Flag don't work

### ISSUE THREAD

**Issue by Raskosk** [kubernetes-sigs/nfs-subdir-external-provisioner#116]
Hello,

I'm trying to use the nfs-provisioner with 2 storage-classes:
The first for persistent data, independent from the container's lifecycle (onDelete: retain) and the second for transient data, depending from the container's lifecycle (onDelete: delete).

For the second one, in case of deleting the PVC (and the PV), I expect PVC, PV and the Files on the NFS-Server to be deleted.
But actually, the files remain on the NFS-Share.
I installed via Kustomize YAML-Files.

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage-transient
provisioner: example.com/nfs-provisioner
parameters:
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
  onDelete: delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage-persistent
provisioner: example.com/nfs-provisioner
parameters:
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
  onDelete: retain
```

The Access Mode is 
`drwxrwxrwx 2 nobody nogroup 4096 Jun 24 14:42 nfs-pv1` 
so the accessing shouldn't be the problem.

Do I need some sort of custom user mapping?
Can anybody help?
