### ISSUE TITLE
Permission problems

### ISSUE THREAD

**Issue by ptitvert** [kubernetes-sigs/nfs-subdir-external-provisioner#129]
Hello,

I don't know if that's the correct place to ask my question, please advice me where is the correct location, in case this is not it.

Our problem is the following, we have an external NFS server using V4, the ID for the files/directories are UID=56008 and GID=56001.
We configure the "nfs-subdir-external-provisioner" like that:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-zy-provisioner
  labels:
    app: nfs-zy-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-zy-provisioner
  template:
    metadata:
      labels:
        app: nfs-zy-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-zy-provisioner
          image: internal.repository.example.com/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-XYZ-zy-provisioner
            - name: NFS_SERVER
              value: externalnfs.example.com
            - name: NFS_PATH
              value: /some/where/down/is/my/path/for/exporting
      volumes:
        - name: nfs-client-root
          nfs:
            server: externalnfs.example.com
            path: /some/where/down/is/my/path/for/exporting
```

That works correctly, then we have another pod where we mount that resource, and here is an example of what we have:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docboss-zy-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-XYZ-zy-nfs-storage"
spec:
  storageClassName: "managed-XYZ-zy-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```

and

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docbase-deployment
spec:
  template:
    spec:
      volumes:
        - name: docboss-zy
          persistentVolumeClaim:
            claimName: docboss-zy-pvc    
      containers:
        - name: docboss
          volumeMounts:
            - name: docboss-zy
              mountPath: /mnt/externalnfs
```

And when I connect to the container, I get the following permissions:

```
drwxrws--- 3 65534 4294967294  73728 Jul  2 07:52 33
drwxrws--- 2 65534 4294967294  69632 Jul  2 07:52 44
drwxrws--- 2 65534 4294967294  90112 Jul  2 07:52 55
-rwxrws--- 1 65534 4294967294 630793 Oct 20  2014 5905001_00001.ZIP
```

So we have the UID=65534 and GID=4294967294.
I've tried to change the fsgroup to 4294967294, but kubernetes is complaining, that it can use number from 0 to 2147483647 inclusive.
I've tried to use supplementalGroups, with the same error message.

My user/group is quite simple:

/etc/passwd:

```
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
nobody:x:99:99:Nobody:/:/sbin/nologin
systemd-network:x:192:192:systemd Network Management:/:/sbin/nologin
dbus:x:81:81:System message bus:/:/sbin/nologin
```

and /etc/group

```
root:x:0:
bin:x:1:
daemon:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mem:x:8:
kmem:x:9:
wheel:x:10:
cdrom:x:11:
mail:x:12:
man:x:15:
dialout:x:18:
floppy:x:19:
games:x:20:
tape:x:33:
video:x:39:
ftp:x:50:
lock:x:54:
audio:x:63:
nobody:x:99:
users:x:100:
utmp:x:22:
utempter:x:35:
input:x:999:
systemd-journal:x:190:
systemd-network:x:192:
dbus:x:81:
ssh_keys:x:998:
sshd:x:74:
```

of course the GID=4294967294 is not available there. I've tried to add a dummy group in /etc/group with GID=4294967294 and assign it to root, and then reconnect to the session, and I cannot enter directories or read the files, because I get a "permission denied". Fair enough.

So all of that to ask, how can I access these files, without asking to change all the files with permission 777?
Is there a way to add a group in /etc/group and assign it to root?
Or better a way to add the original UID/GID and assign it to the root user which is the container running user?
Or do you have any idea that could help solving that problem?

Thank you very much for your help.

Kind regards,
Alessandro
