### ISSUE TITLE
How do we delete EFS access point data using nfs provisioner?

### ISSUE THREAD

**Issue by itsvshreyas** [kubernetes-sigs/nfs-subdir-external-provisioner#133]
We're using NFS Provisioner to provision AWS EFS (PV & PVC) dynamically. Now, when we delete PVC and PV, even though the reclaim policy is set to Delete, access point data does not get deleted from EFS. I'm basically referring to this issue with the usage of NFS Provisioner and not EFS CSI - https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/411. 

NFS Provisioner Version - v3.1.0-k8s1.11

Could someone help us in handling data deletion in the EFS access point using NFS Provisioner after deleting PV and PVC?

**Comment by itsvshreyas** [comment]
Does "onDelete: delete" work for v3.1.0-k8s1.11?

**Comment by ANGkeith** [comment]
Can't get this to work for v4.0.2-k8s1.19.6 too. 

Did you manage to get it to work ?

**Comment by ANGkeith** [comment]
not sure if we are facing the same issue but 


```yaml
USER-SUPPLIED VALUES:
nfs:
  path: /
  server: amazonaws.com
storageClass:
  defaultClass: true
  name: apollo-efs
  onDelete: delete
  reclaimPolicy: Retain      <---- removing this fix the issue for me 
```
