### ISSUE TITLE
How to use mountOptions with Deployment templates?

### ISSUE THREAD

**Issue by ptitvert** [kubernetes-sigs/nfs-subdir-external-provisioner#134]
Hello,
We use such template:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-xy-provisioner
  labels:
    app: nfs-xy-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-xy-provisioner
  template:
    metadata:
      labels:
        app: nfs-xy-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-xy-provisioner
          image: XYZ/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-xxx-xy-provisioner
            - name: NFS_SERVER
              value: myServer.example.com
            - name: NFS_PATH
              value:  /my/path/xy_eingang
      volumes:
        - name: nfs-client-root
          nfs:
            server: myServer.example.com
            path: /my/path/xy_eingang
```
With the following StorageClass:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-xxx-xy-nfs-storage
provisioner: k8s-sigs.io/nfs-xxx-xy-provisioner
parameters:
  pathPattern: ""
  archiveOnDelete: "false"
reclaimPolicy: Retain
```

with the following pv claim

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-xy-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-xxx-xy-nfs-storage"
spec:
  storageClassName: "managed-xxx-xy-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```

The mount in pod:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  template:
    spec:
      volumes:
        - name: app-xy
          persistentVolumeClaim:
            claimName: app-xy-pvc    
      containers:
        - name: app
          volumeMounts:
            - name: app-xy
              mountPath: /my/pod/path/xy
```

I don't know where to put the "nfs.mountOptions", I've tried in several location, and none works.

```
nfs:
  mountOptions:
    - nfsvers=3
```

I've checked the file "charts/nfs-subdir-external-provisioner/templates/deployment.yaml" and I don't see any mountOptions in this file. But since I am quite new on Kubernetes and on "nfs-subdir-external-provisioner", I am a bit lost on how to set it up. We don't use Helm, at all... We are using only templates with Kustomize.

Thanks in advance.

Kind regards,
Alessandro

**Comment by ptitvert** [comment]
I found the solution by myself, since nobody was interested in that question/issue.
I will write it here, so it might help some helpless soul like myself:

In the storage class, you need to add the following options:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-xxx-xy-nfs-storage
provisioner: k8s-sigs.io/nfs-xxx-xy-provisioner
parameters:
  pathPattern: ""
  archiveOnDelete: "false"
reclaimPolicy: Retain
mountOptions:
  - nfsvers=3
```

So simply add the "mountOptions" in the storageClass yaml file.
