### ISSUE TITLE
StorageClass set claimPolicy: Delete,when i delete all pod,it can not delete pvc and pv directory

### ISSUE THREAD

**Issue by AlyssaBetty** [kubernetes-sigs/nfs-subdir-external-provisioner#147]
My StorageClass yaml is:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
mountOptions:
- hard
- nfsvers=4.1
- minorversion=1
- rsize=1048576
- wsize=1048576
- timeo=600
- retrans=2
- noresvport
parameters:
  onDelete: delete
  pathPattern: ${.PVC.namespace}/${.PVC.labels.devGroup}/${.PVC.labels.env}/${.PVC.name}
provisioner: nfs-provisioner-baiducfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

I have set parameters.onDelete = delete ,and set reclaimPolicy: Delete,when I removed all the pods that used SC to automatically generate PVC,but my pv directory can not be delete and it seemed that directory have been saved。what show i do？
