### ISSUE TITLE
Use provisioner for existing NFS shares

### ISSUE THREAD

**Issue by abinet** [kubernetes-sigs/nfs-subdir-external-provisioner#169]
Is it possible to use the provisioner for existing NFS shares?
I have an NFS server with folders configured already. All I need is to create PVs with server/path/mountingoptions dynamically from PVC without creating any subfolders folder in mounted volume. Is it possible with this provisioner?

**Comment by vicyap** [comment]
Hi @abinet, I'm new to this project, but your question sounds very similar to something I was trying to do.

I'm curious what is the use case where you need to create PVs with server/path/mount-options dynamically instead of creating it once, statically, and sharing a PVC with all your pods?

**Comment by abinet** [comment]
Hi @vicyap, thank you for the question. 

I am aware about the discussions here:
https://github.com/kubernetes/kubernetes/issues/60729
https://github.com/kubernetes/community/pull/321#issuecomment-279822350

Hovewer, it is all regarding responsibilities: creating PVs manually must be done by cluster admin only. Creating PVs dynamically from PVC can be done by cluster user with namespace limited permissions.
We can not use NFS v1Volumes because of specific mount options (ver3 etc. ) And as cluster admin I don't want to create PV any time when sobody needs the existing NFS share. Instead of that it would be great just to create a StorageClass with necessary mountOptions and let users create  PVCs.

**Comment by vicyap** [comment]
Is this project closer to what you're looking for? https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/deploy/example

**Comment by abinet** [comment]
unfortunatelly the csi-driver has same limitation- for every PVC it creates a subfolder in NFSs server shared folder and does not allow re-usage  of the existing one.

**Comment by gilesknap** [comment]
Hi, I've come looking for the same feature and my use case is as follows:

I have torn down my entire cluster and rebuilt it because I'm experimenting with IaC. I can recreate my deployments from YAML in a git repo. But I cannot reconnect them to the existing PVCs that are still on my NFS server. I would like to be able to update my deployments to have a permanent shared folder name so that re-creating them from scratch connects them to the same data.

I believe this would match the behaviour of the existingClaim feature of grafana PVCs described here https://medium.com/@kevincoakley/reusable-persistent-volumes-with-the-existingclaim-option-for-the-grafana-prometheus-operator-84568b96315

**Comment by ppenzo** [comment]
I has the same need for both NFS and SMB protocols.

Whereas for SMB it is still a work in progress (see #https://github.com/kubernetes-csi/csi-driver-smb/issues/398), for NFS I've solved it by using the pathPattern parameter in the StorageClass definition and by mounting /persistentvolumes on an EmptyDir volume in the provisioner.

**Comment by vavdoshka** [comment]
@ppenzo can you please elaborate on your workaround?

I thought one can set `customPath` to an empty string to explicitly not create the directory, but it won't work:

https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/0bd4e87b346018eb588cf7e23e6962f195b68a0a/cmd/nfs-subdir-external-provisioner/provisioner.go#L105-L112

**Comment by ppenzo** [comment]
@vavdoshka:
In the provisioner deployment (see: [https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/deploy/deployment.yaml](url)) mount /persistentvolumes to an ephemeral volume, i.e. put 
```
      volumes:
      - emptyDir: {}
        name: nfs-client-root
```
in the deployment.
Then define the corresponding storageclass with these parmeters
```
parameters:
  archiveOnDelete: "false"
  pathPattern: ${.PVC.annotations.nfs.io/storage-path}
```
Hence define the PVC with the annotation nfs.io/storage-path referring the NFS path on the NFS server/Filer referenced by your 
provisioner:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    nfs.io/storage-path: my_share/path/on/filer
  name: mypvc
spec:
  storageClassName: my_filer_sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
```

In this way the provisioner, which AFAIK is not meant for using existing shares, creates/deletes the corresponding nfs path into the ephemeral volume and not on the filer. Nevertheless as far as the path exists on the NFS server everithing works fine.

Obviously you need a separate storage class and provisioner for each NFS server/NAS filer but this shouldn't be an issue.

**Comment by vavdoshka** [comment]
thanks @ppenzo

Interestingly enough but with the last officially released version of the provisioner - `v4.0.2` works for me without the "ephemeral volume" patch. The behavior is if there is no `annotations.nfs.io/storage-path` in the PVC then no namespaced directory gets created, the PV is mounted to the root. But for sure that will not work starting with the version `4.0.8` because of this change https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/83/commits/b8e203661b0b2d3be35342be8869de2125782ebc. And it seems like "ephemeral volume" patch indeed will be the only option until some specific option is implemented probably.

**Comment by MatthewJSalerno** [comment]
This does work with the [cs-driver-nfs](https://github.com/kubernetes-csi/csi-driver-nfs) provisioner is you use the Static Provisioning config.  Their docs are pretty rough, but there's a decent example [here](https://docs.aws.amazon.com/filegateway/latest/files3/use-nfs-csi.html).

**Comment by plsnotracking** [comment]
@ppenzo 

```YAML
      volumes:
      - emptyDir: {}
        name: nfs-client-root
 ```
 
 About this, how did you end up updating the volumes when deploying using the helm chart? I don't see any values being exposed via the `values.yaml`
 
 OR

if anyone has a better way to do this? Thanks.

**Comment by ppenzo** [comment]
@plsnotracking, I did not use the helm chart at all for the deploy.

**Comment by plsnotracking** [comment]
From pointers provided by @ppenzo and @vavdoshka I was able to finally arrive to this solution. I used helm charts to deploy, using ArgoCD. Also the image used by this chart has 3 CVEs. I used another chart.

More info about used chart here: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/330#issuecomment-2153409084

`App.yaml`
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/resource.expiry: "1h"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: nfs-provisioner
    name: target
  project: target
  sources:
    # Chart from Chart Repo
    - chart: nfs-subdir-external-provisioner
      repoURL: https://starttoaster.github.io/nfs-subdir-external-provisioner/
      targetRevision: 4.0.20
      helm:
        valueFiles:
        - $values/path/to/nfs-provisioner/values.yaml
    # Values from Git
    - repoURL: <repo>
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
```

`values.yaml`
```yaml
nfs:
  server: <ip>
  path: <addr>
  mountOptions:
  volumeName: nfs-fancy-name

# For creating the StorageClass automatically:
storageClass:
  # Set a StorageClass name
  # Ignored if storageClass.create is false
  name: nfs-fancy-name

  # Method used to reclaim an obsoleted volume
  reclaimPolicy: Delete

  # Specifies a template for creating a directory path via PVC metadata's such as labels, annotations, name or namespace.
  # Ignored if value not set.
  pathPattern: ${.PVC.annotations.nfs.io/storage-path}

  # Set access mode - ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  accessModes: ReadWriteMany

  # Set volume bindinng mode - Immediate or WaitForFirstConsumer
  volumeBindingMode: Immediate
```

`pvc.yaml`
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: my-namespace
  name: my-pvc
  annotations:
    nfs.io/storage-path: <path/on/nfs/share>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: nfs-fancy-name
```
