### ISSUE TITLE
Support for "CSI Volume Cloning"

### ISSUE THREAD

**Issue by jeliseocd** [kubernetes-sigs/nfs-subdir-external-provisioner#182]
Is it possible to add the feature of PVC cloning? [https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/](url)

When I apply a new PVC with spec.datasource..., like:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-1
    namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 5Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-1
```

* pvc-1 is a previously created PVC in the same namespace and with the same resources.

A new PVC (clone-of-pvc-1) is created but empty.

Thank you!
