### ISSUE TITLE
AWS IAM access

### ISSUE THREAD

**Issue by ArturZurawski** [kubernetes-sigs/nfs-subdir-external-provisioner#192]
Did anyone succeed with using AWS roles to grant access to EFS (not to relay only on security groups)?

I tried helm values with:

```
serviceAccount:
  create: true
  name: nfs-subdir-external-provisioner
  annotations:
    eks.amazonaws.com/role-arn: "${aws_iam_role.nfs_subdir_external_provisioner[0].arn}"
``` 

and role with full access permission but it is not used by pod.

I also tried [Mounting with IAM authorization](https://docs.aws.amazon.com/efs/latest/ug/mounting-IAM-option.html) by providing following options to the helm chart:

```
  mountOptions:
    - tls
    - iam
```

Mounting arguments are updated:
```
Mounting arguments: -t nfs -o iam,tls fs....
```

Web token seems to be defined in env vars:
```
AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token 
```

but no success :( role seems not to be used at all. Am I missing something? Is it even possible?
