### ISSUE TITLE
provisioner pod failed to mount NFS volume

### ISSUE THREAD

**Issue by masteryyh** [kubernetes-sigs/nfs-subdir-external-provisioner#203]
I started a NFS server on a Proxmox host and trying to use this as my K8s storage on two ubuntu guests. After installing via Helm the pod didn't started, describe pod shows this:
```
Name:           nfs-provisioner-nfs-subdir-external-provisioner-869676b747qz27v
Namespace:      default
Priority:       0
Node:           ubuntu-server-0/192.168.2.150
Start Time:     Thu, 19 May 2022 05:40:45 +0000
Labels:         app=nfs-subdir-external-provisioner
                pod-template-hash=869676b747
                release=nfs-provisioner
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/nfs-provisioner-nfs-subdir-external-provisioner-869676b747
Containers:
  nfs-subdir-external-provisioner:
    Container ID:
    Image:          k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      PROVISIONER_NAME:  nfs-provisioner
      NFS_SERVER:        192.168.2.100
      NFS_PATH:          /zfs
    Mounts:
      /persistentvolumes from nfs-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-mzjl2 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  nfs-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pvc-nfs-provisioner-nfs-subdir-external-provisioner
    ReadOnly:   false
  kube-api-access-mzjl2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                             system-role:NoSchedule op=Exists
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  7s (x2 over 21s)  default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         4s                default-scheduler  Successfully assigned default/nfs-provisioner-nfs-subdir-external-provisioner-869676b747qz27v to ubuntu-server-0
  Warning  FailedMount       1s (x4 over 4s)   kubelet            MountVolume.SetUp failed for volume "pv-nfs-provisioner-nfs-subdir-external-provisioner" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o hard,nfsvers=4.2,noacl,proto=tcp 192.168.2.100:/zfs /var/lib/kubelet/pods/c5277ea4-b8e8-4d21-a79f-ab8a610517f0/volumes/kubernetes.io~nfs/pv-nfs-provisioner-nfs-subdir-external-provisioner
Output: mount: /var/lib/kubelet/pods/c5277ea4-b8e8-4d21-a79f-ab8a610517f0/volumes/kubernetes.io~nfs/pv-nfs-provisioner-nfs-subdir-external-provisioner: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.
```

I tried to mount NFS volume manually and it succeeded without any problems.
values.yml:
```
replicaCount: 1
strategyType: Recreate

image:
  repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2
  pullPolicy: IfNotPresent
imagePullSecrets: []

nfs:
  server: 192.168.2.100
  path: /zfs
  mountOptions:
    - hard
    - proto=tcp
    - nfsvers=4.2
    - noacl
  volumeName: nfs-volume
  # Reclaim policy for the main nfs volume
  reclaimPolicy: Retain

# For creating the StorageClass automatically:
storageClass:
  create: true

  # Set a provisioner name. If unset, a name will be generated.
  provisionerName: nfs-provisioner

  # Set StorageClass as the default StorageClass
  # Ignored if storageClass.create is false
  defaultClass: false

  # Set a StorageClass name
  # Ignored if storageClass.create is false
  iname: nfs-storage-class

  # Allow volume to be expanded dynamically
  allowVolumeExpansion: true

  # Method used to reclaim an obsoleted volume
  reclaimPolicy: Retain

  # When set to false your PVs will not be archived by the provisioner upon deletion of the PVC.
  archiveOnDelete: true

  # If it exists and has 'delete' value, delete the directory. If it exists and has 'retain' value, save the directory.
  # Overrides archiveOnDelete.
  # Ignored if value not set.
  onDelete:

  # Specifies a template for creating a directory path via PVC metadata's such as labels, annotations, name or namespace.
  # Ignored if value not set.
  pathPattern:

  # Set access mode - ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  accessModes: ReadWriteOnce

  # Storage class annotations
  annotations: {}

leaderElection:
  # When set to false leader election will be disabled
  enabled: true

## For RBAC support:
rbac:
  # Specifies whether RBAC resources should be created
  create: true

# If true, create & use Pod Security Policy resources
# https://kubernetes.io/docs/concepts/policy/pod-security-policy/
podSecurityPolicy:
  enabled: false

# Deployment pod annotations
podAnnotations: {}

## Set pod priorityClassName
# priorityClassName: ""

podSecurityContext: {}

securityContext: {}

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true

  # Annotations to add to the service account
  annotations: {}

  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations:
  - key: system-role
    operator: Exists
    effect: NoSchedule

affinity: {}

# Additional labels for any resource created
labels: {}
```
