### ISSUE TITLE
How do I add extra NFS mount parameters?

### ISSUE THREAD

**Issue by 2fst4u** [kubernetes-sigs/nfs-subdir-external-provisioner#24]
Is there any way through environment variables to add extra mount parameters? Specifically the "nolock" parameter.

**Comment by yonatankahana** [comment]
since my PR merged, you can build and deploy your own image from `master` and add these mount options in the storage class. for example:

```yaml
kind: StorageClass
metadata:
  name: nfs-nolock
provisioner: my-nfs-client-provisioner
mountOptions:
  - nolock
```
