### ISSUE TITLE
ReclaimPolicy = Retain possible?

### ISSUE THREAD

**Issue by danieniemand** [kubernetes-sigs/nfs-subdir-external-provisioner#243]
Good day,

Is it possible to have the reclaim policy set to retain instead of Delete or Archiving with the word "archive" as prefix?

If so, can you share an example please?

Best Regards

**Comment by Shimrockx** [comment]
Hi,

There's an exemple on patching the name of the storage class so I assumed you can patch the reclaim policy and other options with the same method.

`kustomization.yml`

**Comment by Shimrockx** [comment]
Hi,

There's an exemple on patching the name of the storage class so I assumed you can patch the reclaim policy and other options with the same method.

`kustomization.yml`

```
namespace: nfs-provisioner
bases:
  - github.com/kubernetes-sigs/nfs-subdir-external-provisioner//deploy
resources:
  - namespace.yml
patchesStrategicMerge:
  - patch_nfs_details.yml
patches:
- target:
    kind: StorageClass
    name: nfs-client
  patch: |-
    - op: replace
      path: /reclaimPolicy
      value: Retain
    - op: replace
      path: /allowVolumeExpansion
      value: true
```

Try it with :

```shell
kubectl create -f https://raw.githubusercontent.com/kubernetes-sigs/nfs-subdir-external-provisioner/master/deploy/test-claim.yaml -f https://raw.githubusercontent.com/kubernetes-sigs/nfs-subdir-external-provisioner/master/deploy/test-pod.yaml
```

Wait for success file in the new pod created folder and then use

```shell
kubectl delete -f https://raw.githubusercontent.com/kubernetes-sigs/nfs-subdir-external-provisioner/master/deploy/test-claim.yaml -f https://raw.githubusercontent.com/kubernetes-sigs/nfs-subdir-external-provisioner/master/deploy/test-pod.yaml
```

And look if the folder always exist.

Don't know if it's the best solution but it can help you.
