### ISSUE TITLE
Deleting directory failed because 'storageclass.pathPattern' is defined

### ISSUE THREAD

**Issue by hxp-boy** [kubernetes-sigs/nfs-subdir-external-provisioner#272]
I guess it is because the default path is used when deleting the directory, and the path defined by `pathPattern`  is not used. Hope it can be resolved soon.
# nfs-subdir-external-provisioner   error log：
```bash
I0310 04:37:51.387493       1 controller.go:1450] delete "pvc-3877df78-3015-40f4-b659-c5396c25c3a9": started
W0310 04:37:51.392455       1 provisioner.go:146] path /persistentvolumes/nfs-pvc-test does not exist, deletion skipped
I0310 04:37:51.392481       1 controller.go:1478] delete "pvc-3877df78-3015-40f4-b659-c5396c25c3a9": volume deleted
I0310 04:37:51.400587       1 controller.go:1524] delete "pvc-3877df78-3015-40f4-b659-c5396c25c3a9": persistentvolume deleted
I0310 04:37:51.400606       1 controller.go:1526] delete "pvc-3877df78-3015-40f4-b659-c5396c25c3a9": succeeded
```
```bash
[root@k8s1 ~]# tree /nfs/
/nfs/
└── data
    └── minio-cluster
        └── nfs-pvc-test
```

# nfs-client-provisioner.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: 192.168.0.228
            - name: NFS_PATH
              value: /nfs/data
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.0.228
            path: /nfs/data
```

# class.yaml
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata:
  name: nfs-provisioner-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  onDelete: delete
  pathPattern: "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}"
```

# pvc.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-test
  annotations:
    nfs.io/storage-path: "nfs-pvc-test"
spec:
  storageClassName: "nfs-provisioner-storage"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
```
