### ISSUE TITLE
Cannot change foldername on the folder created by the pvc

### ISSUE THREAD

**Issue by olundberg** [kubernetes-sigs/nfs-subdir-external-provisioner#299]
I am trying to create a backup using NFS on my Synology drive, from the Kubernetes cluster. Everything is working fine, the backups from the mount on the postgres-backup-pod is putting the backups on the NFS system. However, the folder that is created by the PVC is always random (e.g. default-nas-pvc-pvc-616ee266-5037-4252-bc6d-63d923a2b0df). My files are then located within this folder. I would like this folder name to be persistent, but cannot make it work. Ideally I would like to have a name simple as "my_backup" or something.

The command I install with is Helm:

```
$ helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
$ helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=x.x.x.x \
    --set nfs.path=/exported/path
```
This command works fine. Furthermore, my pv and pvc is looking like this:
PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
```
PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-pv
  labels:
spec:
  storageClassName: nfs-client
  claimRef:
    name: nas-pvc
    namespace: default
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 90Gi
  hostPath:
    path: "."
```
This also works fine. And in my deployment (file part) looks like:

```
...
        volumeMounts:
        - mountPath: "/mnt"
          name: nas-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nas-claim0
        persistentVolumeClaim:
          claimName: nas-pvc
...
```

Somehow the "mnt" name is changed to the "random" (default-nas-pvc-pvc-616ee266-5037-4252-bc6d-63d923a2b0df) name, when I would like it to be persistent (pre-defined by me). 

I have tried using the "pathPattern":
```
$ helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=x.x.x.x \
    --set nfs.path=/exported/path \
    --set storageClass=my_backup
```
where I was hoping the random name would go away, without success. I have tried some other numerous "volumeNames" e.g. but then stuff just stops working.
