### ISSUE TITLE
NetworkPolicies are not considered

### ISSUE THREAD

**Issue by wollud1969** [kubernetes-sigs/nfs-subdir-external-provisioner#307]
I've configure a "deny all but dns" network policy

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Egress
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: only-allow-dns
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

```

and about to enable required network traffic within, into and out of the cluster step by step.
However, I've explicitely not yet enabled nfs traffic between the nfs-provisioner pod and the nfs server. Nevertheless, all nfs-client pvc are working and I can see files created in mounts of pods appearing at the nfs server. I can also observe traffic on 2049/tcp on the physical interface of the node where the nfs-provisioner pod is running on.

I've expected, that this traffic is blocked due to the above policies (no others are yet in place), but it isn't.

Is that the behavior you are expecting?

Thank you very much!

P.S.: I've installed the nfs-provisioner this way:

```
#!/bin/bash

# kubectl -f network-policies.yml -n system apply

helm repo add nfs-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
helm repo update
helm upgrade --install -f values.yml nfs-provisioner nfs-provisioner/nfs-subdir-external-provisioner --version 4.0.2 \
  --namespace=system
 
kubectl annotate storageclass local-path storageclass.kubernetes.io/is-default-class-
kubectl annotate storageclass nfs-client storageclass.kubernetes.io/is-default-class=true

```

with `values.yml`:

```
nfs:
  server: 172.16.21.19
  path: /volume1/nfs-storage

```
