### ISSUE TITLE
v4 support and read only mounts

### ISSUE THREAD

**Issue by dberardo-com** [kubernetes-sigs/nfs-subdir-external-provisioner#329]
hi there, my use case:
* use nfs v4
* mount a pre-existing directory from nfs server into container
* do that in a read only mode

so basically i already have data in nfs server and need the container to access that in readonly mode ... 

the problem is that if i create a PVC the provisioner complains with "read only file system" ... which is correct ... but how to achieve this then ?

**Comment by 4censord** [comment]
It sounds like you don't need a provisioner, but a simple PV or just a volume option.
Kubernetes can directly mount NFS as a pod volume.
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /my-nfs-data
      name: test-volume
  volumes:
  - name: test-volume
    nfs:
      server: my-nfs-server.example.com
      path: /my-nfs-volume
      readOnly: true
      # unsure if works
      # mountOptions: []
```

**Comment by dberardo-com** [comment]
thanks for the hint. i indeed was aware of this, but since i am using k3s as distribution, there NFS is not available out of the box so i am not sure what to do to install it

**Comment by 4censord** [comment]
check if your host has all the tools for mounting nfs (e.g. on debian `apt install nfs-common`)
If it still does not work, i'm not sure. Check the docs of k3s maybe

**Comment by dberardo-com** [comment]
hi there, i had checked k3s doc already and could not find out any official way to install a new nfs "storageclass" although i wouldnt call it that way in the case of k8s.

currently i am mounting the nfs volume manually on the host (i.e. outside k8s) and then i pods are accessing via hostPath mount ... which is not ideal of course.

that's why i was looking for a way to deal with it directly in k8s ... should i perhaps try a different approach and use rather a cifs provider ? https://www.datree.io/helm-chart/cifs-share-lippertmarkus

**Comment by 4censord** [comment]
Can you specify again exactly what you are trying to do?
You are confusing me.

In the original post you said you have an NFSv4 server, that already contains data.
You want to mount this into a pod.
It should be mounted read-only.

What i don't get is why you want to use a provisioner for that.

**Comment by dberardo-com** [comment]
i will try that once again, but i recall having given it a shot and it was not working. as also highlighted in this recent post: https://zaher.dev/blog/k3s-with-nfs-storage-class

**Comment by dberardo-com** [comment]
i recently found this post, perhaps this could help installing nfs provisioner in k3s: https://www.phillipsj.net/posts/k3s-enable-nfs-storage/

i believe that my open questions here are:

* can nfs provisioner be used with nfs v4 ?
* can nfs proviosioner be used to mount directories that already exist on the nfs server without the need of creating new directories and without overwirting the existing data
* can the nfs mount be read only --> this was answered above already
* bonus question: is it possible to pass baisc auth credentials to the nfs connection to the server ? i guess this is not natively supported by nfs but is more of a cifs feature, isnt it ?

**Comment by 4censord** [comment]
> can nfs proviosioner be used to mount directories that already exist on the nfs server without the need of creating new directories and without overwirting the existing data

If you want to mount existing directories, you do not need the provisioner. in that case, just create a `pv` per directory manually
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv
spec:
  storageClassName: ""
  nfs:
    server: nfs.example.org
    path: /your/existing path
    readOnly: (true|false)
```
