### ISSUE TITLE
"onDelete: delete" doesn't work if "pathPattern" contains folders

### ISSUE THREAD

**Issue by uniit** [kubernetes-sigs/nfs-subdir-external-provisioner#347]
Consider the following example:
```
➜  ~ helm list -n nfs
NAME                           	NAMESPACE	REVISION	UPDATED                                  	STATUS  	CHART                                 	APP VERSION
nfs-subdir-external-provisioner	nfs      	1       	2024-07-24 17:17:58.678176273 +0200 +0200	deployed	nfs-subdir-external-provisioner-4.0.18	4.0.2
```

Storage Class yaml based on ReadMe:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
parameters:
  onDelete: delete
  pathPattern: /application/dev/${.PVC.annotations.nfs.io/storage-path}
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
reclaimPolicy: Delete
```
PVC yaml based on ReadMe:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    nfs.io/storage-path: app-data
  name: nfs
  namespace: nfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
```

After the PVC removal the nfs provisioner can't find the folder to delete:
```
W0804 10:43:33.486918       1 provisioner.go:146] path /persistentvolumes/app-data does not exist, deletion skipped
```
The only way to get OnDelete working is to not use the folder in the path. See an example [here](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/127).

Question:
Can you please fix that issue or add a note that "onDelete: delete" won't work if "pathPattern" contains folders?

**Comment by aradban** [comment]
For those who come after. `pathPattern` is buggy and should not be used, IMHO. Keep the default, which uses the UUID to guarantee uniqueness. Otherwise you have no protection from name collision, unless you have a very simple environment. The README really needs to be updated to explain this, as the example there uses path syntax.

**Comment by scmanjarrez** [comment]
Not working for me even after removing pathPattern directive

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-appdata-tmp
provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "false"
  #pathPattern: "${.PVC.namespace}/${.PVC.name}-tmp"
allowVolumeExpansion: true
```
