### ISSUE TITLE
OCP3.11 error: can not perform 'use' on 'securitycontextconstraints' in group '' (with fix)

### ISSUE THREAD

**Issue by mclosson-lsf** [kubernetes-sigs/nfs-subdir-external-provisioner#60]
When deploying on Openshift, the README explains that the "hostmount-anyuid" scc needs to be granted to the service account.  When I run the provided command in my OCP3.11 cluster, I get this error message.

```
$ oc create role use-scc-hostmount-anyuid --verb=use --resource=scc --resource-name=hostmount-anyuid -n $NAMESPACE
error: can not perform 'use' on 'securitycontextconstraints' in group ''
```

The `securitycontextconstraints` resource is in the api group `security.openshift.io`.  I appended the following to `rbac.yaml` to get the role added correctly.

```
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-scc-hostmount-anyuid
  namespace: default
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["hostmount-anyuid"]
    verbs: ["use"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-scc-hostmount-anyuid
  namespace: default
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
    namespace: default
roleRef:
  kind: Role
  name: use-scc-hostmount-anyuid
  apiGroup: rbac.authorization.k8s.io
```
