### ISSUE TITLE
clusterrole.yaml not complete, access to nodes are missing

### ISSUE THREAD

**Issue by andreasgremm** [kubernetes-sigs/nfs-subdir-external-provisioner#85]
I needed to add the following to the cluster-role to get pvc's bound.
Header of cluster-role:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: nfs-subdir-external-provisioner
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-03-31T17:23:03Z"
  labels:
    app: nfs-subdir-external-provisioner
    app.kubernetes.io/managed-by: Helm
    chart: nfs-subdir-external-provisioner-4.0.6
    heritage: Helm
    release: nfs-subdir-external-provisioner
```

I added the following:

```
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  ```

Before adding the nodes resources the following error was received:

````
andreas@lubuntu2:~/helm/nfs-client-provisioner$ kubectl describe pvc test-claim
Name:          test-claim
Namespace:     default
StorageClass:  managed-nfs-storage
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
               volume.kubernetes.io/selected-node: vaio2
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       test-pod
Events:
  Type     Reason                Age                   From                                                                                                                                 Message
  ----     ------                ----                  ----                                                                                                                                 -------
  Normal   WaitForFirstConsumer  18m                   persistentvolume-controller                                                                                                          waiting for first consumer to be created before binding
  Normal   ExternalProvisioning  3m43s (x63 over 18m)  persistentvolume-controller                                                                                                          waiting for a volume to be created, either by external provisioner "cluster.local/nfs-subdir-external-provisioner" or manually created by system administrator
  Warning  ProvisioningFailed    2m59s (x7 over 18m)   cluster.local/nfs-subdir-external-provisioner_nfs-subdir-external-provisioner-74577d4bcc-f4c26_726b8f21-71cb-4fc0-ac5c-34d7f6509ae4  failed to get target node: nodes "vaio2" is forbidden: User "system:serviceaccount:default:nfs-subdir-external-provisioner" cannot get resource "nodes" in API group "" at the cluster scope
```
