### ISSUE TITLE
Plex can't write /config on NFS 

### ISSUE THREAD

**Issue by m4dm4rtig4n** [kubernetes-sigs/nfs-subdir-external-provisioner#87]
Hello,

I try to enable persistence config on NFS but Plex don't right to write on /config :/

I have create NFS with nfs-subdir-external-provisioner :
```
nfs:
  server: 192.168.1.10
  path: /volume1/k3s

storageClass:
  name: nfs-k3s
  accessModes: ReadWriteMany
  reclaimPolicy: Retain
```
  
I have create volume + claim :
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-nfs
spec:
  capacity:
    storage: 30Gi
  storageClassName: nfs-k3s
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.10
    path: /volume1/k3s/plex
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-data
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-k3s
  resources:
    requests:
      storage: 30Gi
```

Change values.yaml of Plex.
```
...
persistence:
  config:
    enabled: true
    emptyDir:
      enabled: true
    mountPath: /config 
    accessMode: ReadWriteMany
    storageClass: "nfs-k3s"
    size: 30Gi
    existingClaim: "plex-data"
...
```

And i have always this errors :
```PMS: failure detected. Read/write access is required for path: /config/Library/Application Support/Plex Media Server```

Any Idea ?
