### ISSUE TITLE
Helm does not support archiveOnDelete when setting pathPattern

### ISSUE THREAD

**Issue by psalkowski** [kubernetes-sigs/nfs-subdir-external-provisioner#91]
I do overwrite values like:

```
nfs:
  server: xxx.xxx.xxx.xxx
  path: /mnt/share

storageClass:
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
  archiveOnDelete: "true"
  onDelete: ~
```

But because of pathPattern (maybe because of subdirectories?), it does not archive it. When creating claim and pod, the directory for the claim is created. When removing the claim (and pod), directory is still there. I would assume that there will be something like `archive-default/claim-name`, but nothing happened.

Example pod:
```
kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  volumes:
    - name: local-storage
      persistentVolumeClaim:
        claimName: test-claim
  containers:
    - name: hello-container
      image: busybox
      command:
        - sh
        - -c
        - 'while true; do echo "`date` [`hostname`] Hello from OpenEBS Local PV." >> /mnt/store/greet.txt; sleep $(($RANDOM % 5 + 300)); done'
      volumeMounts:
        - mountPath: /mnt/store
          name: local-storage
```

Example claim:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
```
