### ISSUE TITLE
nfs-subdir-external-provisioner as DaemonSet instead of Deploymet

### ISSUE THREAD

**Issue by egara** [kubernetes-sigs/nfs-subdir-external-provisioner#94]
Hi!

First of all, thank you very much for this amazing project.

We are deploying this controller and we are seeing that, although replicaCount is set to a greater number than 1, all the replicas could be deployed on the same node. The problem is when this node is down. If it happens, all the applications deployed and dependent on the controller will fail until new pods of the controller are recreated again.

Would it be possible to deploy the provisioner as a DaemonSet instead of a Deployment?. This way, at least one pod will be present on every node and this issue would be less problematic. The pods available should only be worried about acquiring the leadership and this time is shorter than recreating the pods within another node I guess.

Thanks again :)

**Comment by yonatankahana** [comment]
another possible solution is to apply [pod anti-affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/).

```yaml
# values.yaml
affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
            operator: In
            values:
            - nfs-subdir-external-provisioner
        topologyKey: "kubernetes.io/hostname"
```

if you don't want to require it but just prefer it, you can use `preferredDuringSchedulingIgnoredDuringExecution` instead.
