### ISSUE TITLE
Wrong directory path used resulting in permission denied for persistent claim

### ISSUE THREAD

**Issue by fbrier** [kubernetes-sigs/nfs-subdir-external-provisioner#98]
I followed the [Helm Readme](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/README.md) and installed the provisioner.
```
microk8s helm3 install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server=127.0.0.1 \
    --set nfs.path=/microk8s-nfs
```
An ext4 partition was mounted at /microk8s-nfs owned by root with a group of microk8s with write access. Is that correct? NFS is configured to export the /microk8s-nfs directory. Included are excerpts of the .yaml files, but I think the problem may be the generated path is wrong. The provisioner log contains:
```
I0503 21:52:15.558277       1 event.go:278] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"data-redmine-postgresql-0", UID:"406328d4-13f4-400a-b110-af8c4bd57b90", APIVersion:"v1", ResourceVersion:"346661", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "nfs-client": unable to create directory to provision new pv: mkdir /persistentvolumes/default-data-redmine-postgresql-0-pvc-406328d4-13f4-400a-b110-af8c4bd57b90: permission denied
Logs from May 3, 2021 to May 3, 2021 UTC
```
Shouldn't the path be /microk8s-nfs/persistentvolumes/default-data-redmine-postgresql-0-pvc-406328d4-13f4-400a-b110-af8c4bd57b90 ? Did I miss some bit of configuration? Thank you.

The persistent claim is pending
```yaml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
status:
  phase: Pending
```
Starting with the spec attribute, the provisioner .yaml is:
```
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
      pod-template-hash: 554695d699
      release: nfs-subdir-external-provisioner
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-subdir-external-provisioner
        pod-template-hash: 554695d699
        release: nfs-subdir-external-provisioner
    spec:
      volumes:
        - name: nfs-subdir-external-provisioner-root
          nfs:
            server: 127.0.0.1
            path: /microk8s-nfs
      containers:
        - name: nfs-subdir-external-provisioner
          image: 'k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2'
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: 127.0.0.1
            - name: NFS_PATH
              value: /microk8s-nfs
          resources: {}
          volumeMounts:
            - name: nfs-subdir-external-provisioner-root
              mountPath: /persistentvolumes
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: nfs-subdir-external-provisioner
      serviceAccount: nfs-subdir-external-provisioner
      securityContext: {}
      schedulerName: default-scheduler
status:
  replicas: 1
  fullyLabeledReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  observedGeneration: 1
```
